### ISSUE TITLE
Find volunteer who submit https://github.com/Homebrew/homebrew

### ISSUE THREAD

**Issue by snmsts** [roswell/homebrew-roswell#4]
I don't like tapping process.

**Comment by takoeight0821** [comment]
I found a Formula of roswell on homebrew-core.
If this Formula doesn't have any problem, maybe this issue was solved.

https://github.com/Homebrew/homebrew-core/blob/971839df1a31f9cee3e315cb100f90ed48aadab7/Formula/roswell.rb

**Comment by snmsts** [comment]
Oh I don't know it. Thank you!
